-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 10:50:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`province`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`province` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`province` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`location` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`location` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `province_id_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `province_id`
    FOREIGN KEY (`province_id`)
    REFERENCES `Pizzeria`.`province` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`client` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`client` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postal_code` CHAR(5) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `location_id_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `Pizzeria`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`store` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`store` (
  `id` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postal_code` CHAR(5) NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_store_location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `Pizzeria`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`order` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`order` (
  `id` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `amount_product` INT NOT NULL,
  `total_price` DOUBLE NOT NULL,
  `client_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `client_id_idx` (`client_id` ASC) VISIBLE,
  INDEX `store_id_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `Pizzeria`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `Pizzeria`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`employee` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`employee` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `store_id_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `Pizzeria`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`home_delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`home_delivery` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`home_delivery` (
  `order_id` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `delivery_person_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_home_delivery_employee1_idx` (`delivery_person_id` ASC) VISIBLE,
  CONSTRAINT `fk_home_delivery_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `Pizzeria`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_home_delivery_employee1`
    FOREIGN KEY (`delivery_person_id`)
    REFERENCES `Pizzeria`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`pick_up`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`pick_up` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`pick_up` (
  `order_id` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `cook_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_pick_up_employee1_idx` (`cook_id` ASC) VISIBLE,
  CONSTRAINT `fk_pick_up_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `Pizzeria`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pick_up_employee1`
    FOREIGN KEY (`cook_id`)
    REFERENCES `Pizzeria`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`product` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`composition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`composition` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`composition` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `Pizzeria`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `Pizzeria`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`category` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`pizza` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`pizza` (
  `product_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_pizza_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_pizza_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Pizzeria`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `Pizzeria`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`hamburger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`hamburger` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`hamburger` (
  `product_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_hamburger_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_hamburger_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Pizzeria`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`drink`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizzeria`.`drink` ;

CREATE TABLE IF NOT EXISTS `Pizzeria`.`drink` (
  `product_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_drink_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_drink_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `Pizzeria`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
