-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 11:10:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cul d'Ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cul d'Ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cul d'Ampolla` DEFAULT CHARACTER SET utf8 ;
USE `Cul d'Ampolla` ;

-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul d'Ampolla`.`client` ;

CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `postal_address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NULL,
  `registration_date` DATE NOT NULL,
  `recommender_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `recommender_id_idx` (`recommender_id` ASC) VISIBLE,
  CONSTRAINT `recommender_id`
    FOREIGN KEY (`recommender_id`)
    REFERENCES `Cul d'Ampolla`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul d'Ampolla`.`address` ;

CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `floor` VARCHAR(45) NULL,
  `door` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `postal_code` CHAR(5) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul d'Ampolla`.`supplier` ;

CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`supplier` (
  `nif` VARCHAR(9) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `fax` VARCHAR(50) NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`nif`),
  INDEX `address_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `Cul d'Ampolla`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`glasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul d'Ampolla`.`glasses` ;

CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`glasses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `graduation` VARCHAR(45) NOT NULL,
  `frame` VARCHAR(45) NOT NULL,
  `frame_color` VARCHAR(45) NOT NULL,
  `crystal_color` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  `supplier_id` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `Cul d'Ampolla`.`supplier` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul d'Ampolla`.`employee` ;

CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul d'Ampolla`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cul d'Ampolla`.`sale` ;

CREATE TABLE IF NOT EXISTS `Cul d'Ampolla`.`sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `glasses_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `glasses_id_UNIQUE` (`glasses_id` ASC) VISIBLE,
  CONSTRAINT `glasses_id`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `Cul d'Ampolla`.`glasses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `client_id`
    FOREIGN KEY (`client_id`)
    REFERENCES `Cul d'Ampolla`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Cul d'Ampolla`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
